services:
  backend:
    image: ghcr.io/zeuswetter/zeus-backend:latest
    ports:
      - "8000:8000"
    networks:
      - zeus-network
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G

  frontend:
    image: ghcr.io/zeuswetter/zeus-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - WEB_APP_API_URL=http://localhost:8000
    networks:
      - zeus-network
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G

networks:
  zeus-network:
    driver: bridge
