name: Build and Push Backend Image

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'ignore-building'
    paths:
      - 'backend/**'

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: emanuelkratz
          password: ${{ secrets.PAT }}

      - name: Build and push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: tags: |
            ghcr.io/ZeusWetter/Zeus-backend:latest
            ghcr.io/ZeusWetter/Zeus-backend:${{ github.ref_name }}
