name: Build and Push Frontend Image

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: tags:|
            ghcr.io/ZeusWetter/Zeus-frontend:latest
            ghcr.io/ZeusWetter/Zeus-frontend:${{ github.ref_name }}
